# Generated by Django 2.1.3 on 2018-11-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historyaddress',
            table='history_address',
        ),
        migrations.AlterModelTable(
            name='preference',
            table='preference',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
