# Generated by Django 2.1.3 on 2018-11-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181107_1807'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historyaddress',
            table='user_history_address',
        ),
        migrations.AlterModelTable(
            name='preference',
            table='user_preference',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_profile',
        ),
    ]
